### ISSUE TITLE
OPR unable to identify input read mates

### ISSUE THREAD

**Issue by geboro** [SushiLab/OPR_Finder#4]
Hello,

I can confirm this error https://github.com/SushiLab/mVIRs/issues/2#issue-851830504 in non-compressed fastq files. 

However, when using compressed files it is consistently failing with the following error:
```
2021-05-21 09:45:59,651 INFO: Starting mVIRs
2021-05-21 09:45:59,677 ERROR: Names of input reads do not match. 
(@WINDU:94:C823GANXX:5:1101:1183:1967/1 != @WINDU:94:C823GANXX:5:1101:1183:1967/2). Check if read files belong together. Quitting
2021-05-21 09:45:59,678 INFO: Finishing mVIRs
```
However, the read names are actually the same, except for the mate pair identifier at the end. This error happens with a variety of FASTQ input files, and is not specific for a single FASTQ file pair.
```
@WINDU:94:C823GANXX:5:1101:1183:1967/1 
@WINDU:94:C823GANXX:5:1101:1183:1967/2
```
Does mVIRs requires a specific FASTQ header modification? 
Cheers!

**Comment by geboro** [comment]
Maybe it would be useful to provide a small test dataset to corroborate a successful installation and to explore the structure of a functioning sample dataset.

**Comment by hjruscheweyh** [comment]
HI @geboro 
We need pairs of sequences to have the identical name to perform downstream analysis correctly. Most paired end files are rather reported with a space, such as:

```
@WINDU:94:C823GANXX:5:1101:1183:1967 1
@WINDU:94:C823GANXX:5:1101:1183:1967 2
```

So the code will work for that dataset. I will have a look into this and come back to you.

Best,
Hans

**Comment by geboro** [comment]
> HI @geboro
> We need pairs of sequences to have the identical name to perform downstream analysis correctly. Most paired end files are rather reported with a space, such as:
> 
> ```
> @WINDU:94:C823GANXX:5:1101:1183:1967 1
> @WINDU:94:C823GANXX:5:1101:1183:1967 2
> ```
> 
> So the code will work for that dataset. I will have a look into this and come back to you.
> 
> Best,
> Hans

Hello!

I can confirm that was the issue. Removed that slash from all reads and it worked! It was very time consuming though, to change them and gzip them back. It would be awesome if the software could recognize both. 

Cheers!

**Comment by hjruscheweyh** [comment]
Unfortunately this restriction cant be lifted as readnames need to match for mVIRs to work. However almost all sequencers have adapted the mode of identical readnames (so without /1 and /2). You issue will most likely not appear in the future. 

If you see it again then you can simply rename your files with a routine from [bbmap](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbmap-guide/)   : 
```bash
bbrename.sh  in1=input.1.fq.gz in2=input.2.fq.gz out1=output.1.fq.gz out2=output2.fq.gz prefix=sample
```

where `sample` can be replaced with any placeholder
